### ISSUE TITLE
Laravel 7 problem in Checkout Page with Stripe JavaScript Form

### ISSUE THREAD

**Issue by abkrim** [LaravelDaily/Laravel-SaaS-Demo-Project#1]
Hi.
First of all thank you very much for the course. Right now my economy is not buoyant and it has been good for me.

I knew in the beginning that I should have used Laravel 6, instead of venturing with Laravel 7.

Now when I have reached the chapter it doesn't work for me. I don't see the part of Vue that should show me the card data request.

If you have any idea why it fails me in Laravel 7 grateful, but I mount the course on 6.X

My repo is owned in my [Gitlab](https://gitlab.castris.com/root/povilas-billing.git)

Best regards

**Comment by PovilasKorop** [comment]
@abkrim hi, it should not be related to Laravel 6/7. Cloned your repository and saw that no plans are visible.

1. Are you sure you have data in "plans" database table? Maybe it's empty?
2. Noticed that you have a weird space symbol before "all()" here, maybe it could be the reason? 
<img width="387" alt="Screen Shot 2020-03-19 at 6 44 07 AM" src="https://user-images.githubusercontent.com/1510147/77032489-318ffc80-69ad-11ea-94f3-48acac600628.png">

**Comment by abkrim** [comment]
Yes.

https://gitlab.castris.com/root/povilas-billing/-/blob/master/app/Http/Controllers/BillingController.php

```
<?php

namespace App\Http\Controllers;

use App\Plan;

class BillingController extends Controller
{
    public function index()
    {
        $plans = Plan:: all();
        return view('billing.index', compact('plans'));
    }
}
```
On Dev Tools I don't see any error

But on PhpStorm i show this on line below **Duplicate script tag**. I've tried comment but also It's not work :
```
<script src="https://js.stripe.com/v3/"></script>
```

Best regards

**Comment by PovilasKorop** [comment]
@abkrim sorry it's hard to guess and debug what is wrong on your end. It worked well for me, so the only reason I think of is "plans" database table is empty. Please try to debug, I can't do that for you remotely.

**Comment by abkrim** [comment]
Not problem. It was just in case you could sound from your experience. I do not want to bother you anymore.
The table has data and I scrupulously follow your steps. I even checked the commit to see if it had left me something.

Now I will reproduce the courses but forcing the installation on LR6, and so I make a diff to see what differences there are. I think the key is in Vue and the different deploy between javascript's LR6 and LR7.

Regards, and thank you very much.
